{% set name = "jupyter_server" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fde612791f716fd34d610cd939704a9639643744751ba66e7ee8fdc9cead07e

build:
  number: 0
  skip: true  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main

requirements:
  host:
    - pip
    - nodejs 18.15.0
    - hatch-jupyter-builder >=0.8.1
    - hatchling >=1.11
    - python
    - setuptools
    - wheel
  run:
    - python
    - anyio >=3.1.0,<4
    - argon2-cffi
    - jinja2
    - jupyter_client >=7.4.4
    - jupyter_core >=4.12,!=5.0.*
    - jupyter_events >=0.4.0
    - jupyter_server_terminals
    - nbconvert >=6.4.4  # avoid hard dependency on pandoc (TODO nbconvert-core???)
    - nbformat >=5.3.0
    - prometheus_client
    # - pywinpty  # [win]  # rely on terminado to get this to keep noarch
    - pyzmq >=24
    - send2trash
    - terminado >=0.8.3
    - tornado >=6.2.0
    - traitlets >=5.6.0
    - websocket-client

test:
  source_files:
    - tests
  requires:
    - pip
    # test deps
    - coverage
    - ipykernel
    - pytest >=7.0
    - pytest-console-scripts
    - pytest-cov
    - pytest-timeout
    - pytest-jupyter-server >=0.6.0
    - requests
  imports:
    - jupyter_server
  commands:
    - pip check
    - jupyter server -h
    - pytest -vvv --cov=jupyter_server -k "not (delete or merge_config)" --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=70
  #downstreams:
    # nodejs >=14,<15 currently isn't available on osx-arm64
    # Skip win because of a false positive pip check fail: jupyter-server 1.13.5 has requirement pywinpty<2
    #- jupyterlab >=3.2  # [not ((osx and arm64) or win or s390x)]
    #- jupyterlab_server >=2.14.0  # [not (linux and s390x)]

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Server
  description: The Jupyter Server provides the backend for Jupyter web applications such as the Jupyter notebook and JupyterLab.
  dev_url: https://github.com/jupyter/jupyter_server
  doc_url: https://jupyter-server.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
    - bollwyvl
    - Zsailer
