{% set name = "jupyter_server" %}
{% set version = "2.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12558d158ec7a0653bf96cc272bc7ad79e0127d503b982ed144399346694f726
  patches:
    # tests fail on some platforms because server doesn't start as
    # root by default
    - 00_allow_root_in_tests.patch

build:
  number: 0
  # This package depends on nodejs, which isn't available on s390x because it's not included in SOW packages
  skip: true  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main

requirements:
  build:
    - patch    # [not win]
    - m2-patch # [win]
  host:
    - pip
    - nodejs 18.16.0
    - hatch-jupyter-builder >=0.8.1
    - hatchling >=1.11
    - python
  run:
    - python
    - anyio >=3.1.0
    - argon2-cffi >=21.1
    - jinja2 >=3.0.3
    - jupyter_client >=7.4.4
    - jupyter_core >=4.12,!=5.0.*
    - jupyter_events >=0.9.0
    - jupyter_server_terminals >=0.4.4
    - nbconvert >=6.4.4  # avoid hard dependency on pandoc (TODO nbconvert-core???)
    - nbformat >=5.3.0
    - packaging >=22.0
    - prometheus_client >=0.9
    - pywinpty >=2.0.1 # [win]
    - pyzmq >=24
    - send2trash >=1.8.2
    - terminado >=0.8.3
    - tornado >=6.2.0
    - traitlets >=5.6.0
    - websocket-client >=1.7
    - overrides >=5.0

{% set xtests = [ "test_culling" ] %}

# test_restart_kernel does not seem to be problematic in standalone testing, but is flaky in the
# current anaconda build env
{% set xtests = xtests + ["test_restart_kernel[jp_server_config0]", "test_connection[jp_server_config0]"] %}

# some tests aren't working on windows due shell config in the anaconda build env
# Error: "FileNotFoundError: The command was not found or was not executable: /bin/bash"
{% set xtests = xtests + ["test_terminal", "test_authorized_requests"]  %} # [ win ]

{% set tests = "not (" + " or ".join(xtests) + ")" %}

test:
  source_files:
    - tests
  requires:
    - pip
    # test deps
    - coverage
    - ipykernel
    - posix # [win]
    - pytest >=7.0,<9
    - pytest-console-scripts
    - pytest-cov
    - pytest-timeout
    - pytest-jupyter-server >=0.7
    - requests
    - flaky
  imports:
    - jupyter_server
  commands:
    - pip check
    - jupyter server -h
    - echo "{{ tests }}"
    - pytest -vvv --cov=jupyter_server -k "{{ tests }}" --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=70
  #downstreams:
    #- jupyterlab
    #- jupyterlab_server

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Server
  description: The Jupyter Server provides the backend for Jupyter web applications such as the Jupyter notebook and JupyterLab.
  dev_url: https://github.com/jupyter/jupyter_server
  doc_url: https://jupyter-server.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
    - bollwyvl
    - Zsailer
