{% set name = "jupyter_server" %}
{% set version = "1.1.2" %}
{% set sha256 = "b4b1f8f0c38e1faf418f3ff536cdb6d84dfb477d150abee5f0e65c7fd95fa527" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main
    - jupyter-bundlerextension = jupyter_server.bundlerextensions:main
  skip: true  # [py36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipython_genutils
    - jinja2
    - jupyter_core >=4.4.0
    - jupyter_client >=6.1.1
    - nbconvert
    - nbformat
    - pyzmq >=17
    - send2trash
    - terminado >=0.8.3
    - tornado >=6.1
    - traitlets >=4.2.1
    - prometheus_client
    - pywin32 >=1.0  # [win]
    - anyio >=2.0.2

test:
  commands:
    - jupyter server -h
  imports:
    - jupyter_server

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Jupyter Server
  description: The Jupyter Server provides the backend for Jupyter web applications such as the Jupyter notebook and JupyterLab.
  dev_url: https://github.com/jupyter/jupyter_server

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
