{% set name = "jupyter_server" %}
{% set version = "1.23.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ee4f311bd944bcf8060a8b746059571c40f6b8ada1d1e6e51239d26ab23b15c

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main

requirements:
  host:
    - python
    # To avoid ImportError: cannot import name 'StaticModule' from 'setuptools.config'
    # we should use jupyter-packaging >=0.12.0
    - jupyter-packaging >=0.12.0,<1
    - pip
    - setuptools
    - wheel
  run:
    - python
    - anyio >=3.1.0
    - argon2-cffi
    - jinja2
    - jupyter_client >=6.1.12
    - jupyter_core >=4.7.0
    - nbconvert >=6.4.4  # avoid hard dependency on pandoc
    - nbformat >=5.2.0
    - packaging
    - prometheus_client
    - pywinpty  # [win]
    - pyzmq >=17
    - send2trash
    - terminado >=0.8.3
    - tornado >=6.1.0
    - traitlets >=5.1
    - websocket-client

test:
  requires:
    - pip
  commands:
    - pip check
    - jupyter server -h
  imports:
    - jupyter_server
  #downstreams:
    # nodejs >=14,<15 currently isn't available on osx-arm64
    # Skip win because of a false positive pip check fail: jupyter-server 1.13.5 has requirement pywinpty<2
    #- jupyterlab >=3.2  # [not ((osx and arm64) or win or s390x)]
    #- jupyterlab_server >=2.14.0  # [not (linux and s390x)]

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Jupyter Server
  description: The Jupyter Server provides the backend for Jupyter web applications such as the Jupyter notebook and JupyterLab.
  dev_url: https://github.com/jupyter/jupyter_server
  doc_url: https://jupyter-server.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
    - bollwyvl
    - Zsailer
