travis:
  secure:
    BINSTAR_TOKEN: XTP3ToEO103O2b7XwPNmGTvYUYHMYPLQtAuErhwZ8kcPurLKd2FkV8BFTr6fT33JdafI1+zR7Vaz2UND+Ma4iiqJaESwRxpKJmC1CRRLu9PRxEjJ/cRwDU26niRtSQE9rtFjQVXYmgL8xNEwiB2Wd3Hq295/pqeAkbfr8ZqDBuB4bAJro42dJJ9HzeZ8sKnVNbi787Q0OPAQXM8l7Fzex6m8rmzk3DfWDZHQMezvmPuKbrzTdVmasLhVS0JKuBqQUZCPbpx62H/9h6TilKYawR5JdWbukozgXABg50cM7Xq2nY3X4YJtwDKdDBPiUsxwm3AhjriQMcGLDMN+lyYCMZHu+TTIPVjsqqv9SDB1IPD+Z6jqVxVwdKwT1BmZV56QXADTHNb9gRXdFhnHnjWxxvSOobkooA1CJW2pRJx6N1mzPMCW3474Ii+OECUm2Fa2KzQ9EmNyKnzoh0+HxPAdAqsMqKonw7u6wxRgsEeeYLAsY/xtjcD/GnDrEu8yVxaKWMLJw+6tcHAdS42kXNRRrH3MdhNLkqIGM7FmwJEyd50CZpexdQtq/c9osPqGgHPB9x8tBOhrwYdzUau/2InEDgZY/fe8REkzgzQh9mDf5hqsunWT6kQ2HAH3zA76/9FafkIs5bXeVnmEmLdvxlrGtc64rjAeBKZt2Q4sFTF5i2o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
